"""empty message

Revision ID: 062babf266ce
Revises: b3fb95bb0254
Create Date: 2024-07-13 22:56:38.000194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062babf266ce'
down_revision = 'b3fb95bb0254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_table', schema=None) as batch_op:
        batch_op.drop_constraint('feedback_table_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_table', schema=None) as batch_op:
        batch_op.create_unique_constraint('feedback_table_email_key', ['email'])

    # ### end Alembic commands ###
