"""empty message

Revision ID: 5a01e707d7f8
Revises: 0a203e4f0915
Create Date: 2024-07-14 20:47:48.841070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a01e707d7f8'
down_revision = '0a203e4f0915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders_table', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('shipping_address',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('mailing_address',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('credit_card_info',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders_table', schema=None) as batch_op:
        batch_op.alter_column('credit_card_info',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('mailing_address',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.alter_column('shipping_address',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
