"""empty message

Revision ID: a2e1f536553f
Revises: 
Create Date: 2024-07-22 02:34:33.762242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e1f536553f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoes_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('size', sa.String(length=120), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('full_name')
    )
    op.create_table('billing_address_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('card_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.String(length=16), nullable=False),
    sa.Column('cvv', sa.String(length=3), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('month', sa.String(length=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num')
    )
    op.create_table('favorites_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shoe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shoe_id'], ['shoes_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipping_address_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('orders_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('billing_address_id', sa.Integer(), nullable=True),
    sa.Column('shipping_address_id', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('order_date', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['billing_address_id'], ['billing_address_table.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['card_table.id'], ),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['shipping_address_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shoes_ordered',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('shoe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders_table.id'], ),
    sa.ForeignKeyConstraint(['shoe_id'], ['shoes_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shoes_ordered')
    op.drop_table('orders_table')
    op.drop_table('shipping_address_table')
    op.drop_table('feedback_table')
    op.drop_table('favorites_table')
    op.drop_table('card_table')
    op.drop_table('billing_address_table')
    op.drop_table('user_table')
    op.drop_table('shoes_table')
    # ### end Alembic commands ###
