"""empty message

Revision ID: b3fb95bb0254
Revises: 8bbbcee0bcc8
Create Date: 2024-07-13 22:50:38.345659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3fb95bb0254'
down_revision = '8bbbcee0bcc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_table', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.String(length=300),
               existing_nullable=False)
        batch_op.drop_constraint('feedback_table_description_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_table', schema=None) as batch_op:
        batch_op.create_unique_constraint('feedback_table_description_key', ['description'])
        batch_op.alter_column('description',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=600),
               existing_nullable=False)

    # ### end Alembic commands ###
